apiVersion: v1
kind: Service
metadata:
  name: jekyllapp-ENVIRONMENT
  labels:
    app: jekyllapp-ENVIRONMENT
spec:
  # type: NodePort 
  
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: jekyllapp-ENVIRONMENT
